# Generated by Django 6.1.1 on 2026-10-02 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investmentcategory_remove_investment_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.investmentplan'),
        ),
    ]
