# Generated by Django 6.1.1 on 2026-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualfundingrequest',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
