# Generated by Django 6.1.1 on 2026-10-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_manualfundingrequest_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualfundingrequest',
            name='crypto_amount',
        ),
        migrations.RemoveField(
            model_name='manualfundingrequest',
            name='transaction_hash',
        ),
    ]
