# Generated by Django 6.1.1 on 2026-10-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_manualfundingrequest_crypto_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualfundingrequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
