# Generated by Django 6.1.1 on 2026-09-29 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__gt', '')), fields=('provider', 'provider_reference'), name='unique_provider_reference'),
        ),
    ]
