# Generated by Django 6.1.1 on 2026-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
